### ISSUE TITLE
Support for rails 5?

### ISSUE THREAD

**Issue by cha55son** [kares/activerecord-bogacs#1]
I'm testing this with Rails 5. I've added the gem to the Gemfile and I get the following error: (also set `connection_pool_class` but still get the error)

```
Caused by: org.jruby.exceptions.RaiseException: (ArgumentError) wrong number of arguments (1 for 2)
	at RUBY.establish_connection(.../activerecord-bogacs-0.5.0/lib/active_record/bogacs.rb:61)
	at RUBY.establish_connection(.../activerecord-5.0.2/lib/active_record/connection_handling.rb:61)
	at RUBY.block in Railtie(.../activerecord-5.0.2/lib/active_record/railtie.rb:125)
```

Not sure why `establish_connection` is expecting more than one parameter. Anyway i'm going to dive in a bit further but thought I would bring it up in case someone else knows a quick fix.

**Comment by cha55son** [comment]
Yea looks like Rails 5 changed how they are calling `establish_connection` on it's connection handler.

Rails 4.1.x: https://github.com/rails/rails/blob/v4.1.16/activerecord/lib/active_record/connection_handling.rb#L57
Rails 5.x: https://github.com/rails/rails/blob/v5.1.0.rc1/activerecord/lib/active_record/connection_handling.rb#L58

I'll play around with this and see if there are more issues that arise.

**Comment by cha55son** [comment]
Here's what I got working for Rails 5. Also it directly replaces the `ConnectionPool` class in ActiveRecord so it removes an extra layer of monkey patching. (Since AR uses autoloading this works fine)

https://gist.github.com/cha55son/2486a6b10374f12387e2a4e9a1e194c4

**Comment by kares** [comment]
hey! there's probably several issues - AR-JDBC might be an issue as well (not supporting AR 5 well enough).
would be great to have a back-wards compatible patch to run smoothly with AR 5 - thus patching is required.
